repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args:
          [
            "--line-length",
            "90",
            "--force-exclude",
            "banners.py",
            "--target-version",
            "py310",
          ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
